# show coverage in CI status, not as a comment. Never consider it a failure.
comment: off
coverage:
  status:
    project:
      default:
        target: 0%
    patch:
      default:
        target: 0%
